export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_COMPLETE = 'FETCH_PRODUCTS_COMPLETE';
export const FETCH_PRODUCTS_THROTTLE = 'FETCH_PRODUCTS_THROTTLE';
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
